/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-12-2: 23h:10m
**
*/

var statmp16

function
__patsfun_1__closurerize(env0, env1)
{
  return [function(cenv, arg0) { return __patsfun_1(cenv[1], cenv[2], arg0); }, env0, env1];
}


function
__patsfun_6__closurerize(env0)
{
  return [function(cenv) { return __patsfun_6(cenv[1]); }, env0];
}


function
__patsfun_8__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_8(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_10__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_10(arg0, arg1); }];
}


function
__patsfun_11__closurerize()
{
  return [function(cenv) { return __patsfun_11(); }];
}


function
_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__kfact(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmp1
  var tmp2
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_kfact
    tmp1 = ats2jspre_gt_int0_int0(arg0, 0);
    if(tmp1) {
      tmp2 = ats2jspre_sub_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp2;
      apy1 = __patsfun_1__closurerize(arg0, arg1);
      arg0 = apy0;
      arg1 = apy1;
      funlab_js = 1; // __patsflab_kfact
      // ATStailcalseq_end
    } else {
      arg1[0](arg1, 1);
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
__patsfun_1(env0, env1, arg0)
{
//
// knd = 0
  var tmp4
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_1
  tmp4 = ats2jspre_mul_int0_int0(arg0, env0);
  env1[0](env1, tmp4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__fact(arg0)
{
//
// knd = 0
  var tmpret5
  var tmplab, tmplab_js
//
  // __patsflab_fact
  tmpret5 = aux_3(arg0, 1);
  return tmpret5;
} // end-of-function


function
aux_3(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret6
  var tmp7
  var tmp8
  var tmp9
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_aux_3
    tmp7 = ats2jspre_gt_int0_int0(arg0, 0);
    if(tmp7) {
      tmp8 = ats2jspre_sub_int0_int0(arg0, 1);
      tmp9 = ats2jspre_mul_int0_int0(arg1, arg0);
      // ATStailcalseq_beg
      apy0 = tmp8;
      apy1 = tmp9;
      arg0 = apy0;
      arg1 = apy1;
      funlab_js = 1; // __patsflab_aux_3
      // ATStailcalseq_end
    } else {
      tmpret6 = arg1;
    } // end-of-if
    if (funlab_js > 0) continue; else return tmpret6;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__the_facts()
{
//
// knd = 0
  var tmpret10
  var tmplab, tmplab_js
//
  // __patsflab_the_facts
  tmpret10 = the_facts_helper_5(1);
  return tmpret10;
} // end-of-function


function
the_facts_helper_5(arg0)
{
//
// knd = 0
  var tmpret11
  var tmplab, tmplab_js
//
  // __patsflab_the_facts_helper_5
  tmpret11 = ATSPMVlazyval(__patsfun_6__closurerize(arg0));
  return tmpret11;
} // end-of-function


function
__patsfun_6(env0)
{
//
// knd = 0
  var tmpret12
  var tmp13
  var tmp14
  var tmp15
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_6
  tmp13 = _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__fact(env0);
  tmp15 = ats2jspre_add_int0_int0(env0, 1);
  tmp14 = the_facts_helper_5(tmp15);
  tmpret12 = [tmp13, tmp14];
  return tmpret12;
} // end-of-function


function
_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__stream_kforeach(arg0, arg1, arg2)
{
//
// knd = 0
  var tmp18
  var tmp19
  var tmp20
  var tmplab, tmplab_js
//
  // __patsflab_stream_kforeach
  tmp18 = ATSPMVlazyval_eval(arg0); 
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab0
      if(ATSCKptriscons(tmp18)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab1
      arg2[0](arg2);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab2
      case 4: // __atstmplab3
      tmp19 = tmp18[0];
      tmp20 = tmp18[1];
      arg1[0](arg1, tmp19, __patsfun_8__closurerize(arg1, arg2, tmp20));
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
__patsfun_8(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_8
  if(arg0) {
    _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__stream_kforeach(env2, env0, env1);
  } else {
    env1[0](env1);
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
the_facts_start()
{
//
// knd = 0
  var tmp28
  var tmp30
  var tmplab, tmplab_js
//
  // __patsflab_the_facts_start
  tmp28 = __patsfun_10__closurerize();
  tmp30 = __patsfun_11__closurerize();
  _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__stream_kforeach(statmp16, tmp28, tmp30);
  return/*_void*/;
} // end-of-function


function
__patsfun_10(arg0, arg1)
{
//
// knd = 0
  var tmp24
  var tmp25
  var tmp26
  var tmp27
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_10
  tmp27 = ats2jspre_String(arg0);
  tmp26 = ats2jspre_string_append("factorial= ", tmp27);
  tmp25 = ats2jspre_string_append(tmp26, ". Continue?");
  tmp24 = ats2jspre_confirm(tmp25);
  arg1[0](arg1, tmp24);
  return/*_void*/;
} // end-of-function


function
__patsfun_11()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_11
  ats2jspre_alert("Stopped");
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__dynloadflag = 0;

function
_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__dynloadflag(97))
  if(ATSCKiseqz(_057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__dynloadflag)) {
    _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__dynloadflag = 1 ; // flag is set
    statmp16 = _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__the_facts();
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
fact__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_alexander_057_Documents_057_JavaScriptFiles_057_CPS_055_counters_057_CPS_055_factorial_057_CPS_factorial_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
function
fact__initize()
{
//
fact__dynload(); return;
//
} // end of [fact__initize]
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
jQuery(document).ready(function(){fact__initize();});
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
